mrc-5105: Add has_modifications flag to report list endpoint
mrc-ide/orderly.runner pull request #3
Opened 2024-02-29 10:36 UTC by r-ash

To indicate when a particular report has modifications from the default branch.

We want this because in the UI when users view the list of reports, we want to have a checkbox to show only those reports which contain modifications (if the user has selected a branch other than the default branch)

This will always return `has_modifications` even if the hash this is called with the default branch or a hash which is on the default branch.

This gets the default branch from the `gert::git_remote_info("origin")`. This is the `HEAD branch` from the remote origin, which if I understand correctly should always be the GitHub default branch.

This gets the modified files using `git diff <from>...<to>` using the remote origin as the `<from>` branch. This is the same as what `orderly.server` is doing at the moment. I expect we could probably make an enhancement in `gert` to be able to call `gert::git_diff()` with a specified base ref but can do that later.

2024-02-29 10:39 UTC, r-ash commented on R/api.R
> +##'   query ref :: string
I changed this to ref too because I think this is better description, it can work with a hash or a branch name

2024-03-01 13:32 UTC, richfitz requested changes

2024-03-01 13:32 UTC, richfitz commented on R/git.R
> +git_ref_to_sha <- function(ref, repo = NULL, check = FALSE) {
Is this not `gert::git_commit_id`?

2024-03-01 13:32 UTC, richfitz commented on R/git.R
> +git_get_modified <- function(ref, base = NULL,
we should make a ticket to patch gert for this perhaps

2024-03-01 13:32 UTC, richfitz commented on R/util_assert.R
> +}
consider invisible return of x on all of these (not needed on assert_scalar_character as that's implicit) as that's often useful

2024-03-01 17:27 UTC, r-ash commented on R/git.R
> +git_ref_to_sha <- function(ref, repo = NULL, check = FALSE) {
It absolutely is yes, thanks!

2024-03-01 17:30 UTC, r-ash commented on R/git.R
> +git_get_modified <- function(ref, base = NULL,
Agreed, added a ticket for this https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-5126/Update-gert-to-be-able-to-get-diff-with-...-syntax

2024-03-04 09:24 UTC, richfitz approved these changes

2024-03-04 09:24 UTC, richfitz commented on R/util_assert.R
> +assert_scalar <- function(x, name = deparse(substitute(x)), arg = name,
After your change you no longer need these :) but they're bound to come in useful lter

2024-03-04 09:24 UTC, richfitz commented on tests/testthat/test-util-assert.R
> +  expect_error(assert_scalar(1:2), "must be a scalar")
```suggestion
  expect_error(assert_scalar(1:2), "must be a scalar")
  expect_no_error(assert_scalar(1))
```

2024-03-05 16:56 UTC, M-Kusumgar approved these changes
LGTM!

2024-03-05 17:11 UTC, merged